name: Compile kernel

on:
  workflow_dispatch:

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Get ZyC Clang
        run: mkdir clang
             wget -qO clang.tar.gz https://github.com/ZyCromerZ/Clang/releases/download/16.0.6-20260510-release/Clang-16.0.6-20260510.tar.gz
             tar -xf clang.tar.gz -C clang
             rm clang.tar.gz
        

      - name: Compile kernel
        run: ./scripts/RvCompiler/compile.sh DEFCONFIG=vendor/xiaomi/alioth_defconfig CLANG_DIR=$PWD/clang KBUILD_BUILD_USER=Rve KBUILD_BUILD_HOST=RvEnterprises

      - name: Upload Image & DTBO
        uses: actions/upload-artifact@v4
        with:
          name: RvKernel-Alioth
          path: |
            out/arch/arm64/boot/Image
            out/arch/arm64/boot/dtb.img
            out/arch/arm64/boot/dtbo.img

      - name: Upload log
        uses: actions/upload-artifact@v4
        with:
          name: compile-log
          path: out/compile.log
